## **Numpy Pandas Assignment**

In [35]:
import numpy as np

In [36]:
import pandas as pd

# *Task1: Numpy Basics*

#  Array Creation

In [37]:
##1D and 2D numpy array

In [38]:
arr_1D = np.array([1,2,3,4]) #cant use numeric value at 1st of any variabel

In [39]:
print ("1D_array", arr_1D)

1D_array [1 2 3 4]


In [40]:
arr_2D = np.array([[1,2,3],[4,5,6]])

In [41]:
print ("2D_array",arr_2D)

2D_array [[1 2 3]
 [4 5 6]]


In [42]:
print ("2D_array:\n",arr_2D) #n is used to start a new line

2D_array:
 [[1 2 3]
 [4 5 6]]


# Array Operation

In [43]:
##Performing basic arithmatic operations in array

In [44]:
arr_add = arr_1D + 10 #adding above 1D array by 10 that will add 10 to every elements inside array

In [45]:
print("Sum",arr_add)

Sum [11 12 13 14]


In [46]:
arr_mul = arr_2D *2 #multipying above 2D array by 2

In [47]:
print("Mul\n",arr_mul)

Mul
 [[ 2  4  6]
 [ 8 10 12]]


# Indexing And Slicing

In [48]:
##Demonstrating Indeximg and Slicing in Array

In [49]:
print("First element of 1Darray :",arr_1D[1]) ## [1] gives the value in index 1

First element of 1Darray : 2


In [50]:
print ("First row of 2Darray:\n",arr_2D[0,:])

First row of 2Darray:
 [1 2 3]


# Shaping and Reshaping Array

In [51]:
##checking shape and reshaping array

In [52]:
print ("shape of 2Darray:",arr_2D.shape)

shape of 2Darray: (2, 3)


In [53]:
reshape_2Darr = arr_2D.reshape((3,2))

In [54]:
print("Reshaped array:\n",reshape_2Darr)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


# *Task 2:Pandas Basics*

# Series and Dataframe Creation

In [55]:
s=pd.Series([1,2,3,4,5])

In [56]:
print("Pandas Series:\n",s)

Pandas Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [57]:
##Dataframe

In [58]:
df = pd.DataFrame({'A':[1,2,3,4],
                 'B':[5,6,7,8],
                  'c':[1,5,3,4]})

In [59]:
print("DataFrame:\n",df)

DataFrame:
    A  B  c
0  1  5  1
1  2  6  5
2  3  7  3
3  4  8  4


# Reading Data

In [60]:
#Reading data from a csv file

In [61]:
df_read = pd.read_csv('/Users/bandanaadhikari/Desktop/classassignment/Sample_Data.csv')

In [62]:
df_read.head()

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

# Data Inspection

In [ ]:
#performing basic data inspection method

In [63]:
print ("head of DataFrame:\n",df.head())

head of dataframe:
    A  B  c
0  1  5  1
1  2  6  5
2  3  7  3
3  4  8  4


In [64]:
print ("info of DataFrame:\n",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   c       4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes
info of DataFrame:
 None


In [66]:
print ("description of DataFrame:\n",df.describe())

description of DataFrame:
               A         B         c
count  4.000000  4.000000  4.000000
mean   2.500000  6.500000  3.250000
std    1.290994  1.290994  1.707825
min    1.000000  5.000000  1.000000
25%    1.750000  5.750000  2.500000
50%    2.500000  6.500000  3.500000
75%    3.250000  7.250000  4.250000
max    4.000000  8.000000  5.000000


# Data Manipulation 

In [67]:
#selection of data

In [69]:
print ("Column A:\n",df[['A']])

Column A:
    A
0  1
1  2
2  3
3  4


In [73]:
print("column A and B:\n",df[['A','B']])

column A and B:
    A  B
0  1  5
1  2  6
2  3  7
3  4  8


#Filtering Data


In [74]:
filtered_df = df[df['A']>1]

In [75]:
filtered_df

A  B  c
1  2  6  5
2  3  7  3
3  4  8  4

In [76]:
# Adding/Removing Columns


In [100]:
df['D']=df['A']+df['B']

In [101]:
df['D']

0     6
1     8
2    10
3    12
Name: D, dtype: int64

In [102]:
df.drop('D', axis=1, inplace =True) #DataFrame after dropping column D

In [94]:
df

A  B  c   D
0  1  5  1   6
1  2  6  5   8
2  3  7  3  10
3  4  8  4  12

In [103]:
# Handling Missing Data

In [104]:
df_with_nan = df.copy()

In [105]:
df_with_nan.loc[1, 'B'] = np.nan

In [106]:
print("DataFrame with NaN:\n", df_with_nan)

DataFrame with NaN:
    A    B  c
0  1  5.0  1
1  2  NaN  5
2  3  7.0  3
3  4  8.0  4


In [107]:
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())

DataFrame after dropping NaN:
    A    B  c
0  1  5.0  1
2  3  7.0  3
3  4  8.0  4


In [108]:
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

DataFrame after filling NaN with 0:
    A    B  c
0  1  5.0  1
1  2  0.0  5
2  3  7.0  3
3  4  8.0  4


# Task 3: Data Analysis with Pandas

In [109]:
# Aggregations

In [110]:
print("Mean of column A:", df['A'].mean())

Mean of column A: 2.5


In [111]:
print("Sum of column A:", df['A'].sum())

Sum of column A: 10


In [112]:
# Merging and Joining

In [113]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})

In [114]:
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})

In [115]:
merged_df = pd.merge(df1, df2, on='key', how='inner')

In [129]:
print("Merged DataFrame:\n", merged_df)


Merged DataFrame:
   key  value_x  value_y
0   A        1        4
1   B        2        5


In [130]:
# Time Series Analysis


In [131]:
df['date'] = pd.date_range(start='1/1/2020', periods=len(df), freq='D')

In [132]:
df.set_index('date', inplace=True)

In [133]:
print("DataFrame with Date Index:\n", df)


DataFrame with Date Index:
             A  B  c
date               
2020-01-01  1  5  1
2020-01-02  2  6  5
2020-01-03  3  7  3
2020-01-04  4  8  4


In [134]:
resampled_df = df.resample('M').mean()


In [135]:
print("Resampled DataFrame:\n", resampled_df)

Resampled DataFrame:
               A    B     c
date                      
2020-01-31  2.5  6.5  3.25
